GET http://localhost:8080/mvc/rest/v1/product/all


###

POST  http://localhost:8080/mvc/rest/v1/product
Content-Type: application/json

    {

      "title": "Product 10",
      "description": "Loose",
      "cost": 2080
    }

###

PUT  http://localhost:8080/mvc/rest/v1/product
Content-Type: application/json

   {
      "id": 12,
      "title": "Product 14",
      "description": "Liquid",
      "cost": 30101
    }
